# Generated by Django 4.2.1 on 2024-04-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_produit_facture_facture_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='produit',
        ),
        migrations.AddField(
            model_name='produit',
            name='facture',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='stock.facture'),
            preserve_default=False,
        ),
    ]
