# Generated by Django 4.2.1 on 2024-04-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_remove_facture_produit_produit_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='facture',
        ),
        migrations.CreateModel(
            name='FactureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=132)),
                ('Devis_date_time', models.DateField(auto_now_add=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
    ]
