# Generated by Django 4.2.1 on 2024-04-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_produit_facture_factureproduct_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduct',
            name='quantity_achat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
