# Generated by Django 5.0.4 on 2024-04-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_produit_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureproduct',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.produit'),
        ),
    ]
