# Generated by Django 5.0.4 on 2024-04-24 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_factureproduct_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureproduct',
            name='produit',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.CASCADE, to='stock.produit'),
            preserve_default=False,
        ),
    ]
