# Generated by Django 5.0.4 on 2024-04-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_factureproduct_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='facture_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
