# Generated by Django 5.0.4 on 2024-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_facture_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduct',
            name='price_finich',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
