# Generated by Django 3.2.1 on 2024-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_factureproduct_price_finich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='facture_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
