# Generated by Django 3.2.1 on 2024-04-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_facture_facture_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
