# Generated by Django 3.2.1 on 2024-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_facture_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='facture_date_time',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
