# Generated by Django 3.2.1 on 2024-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_facture_facture_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='facture_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
