# Generated by Django 3.2.1 on 2024-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_facture_facture_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='total',
            field=models.IntegerField(),
        ),
    ]
