# Generated by Django 3.2.1 on 2024-04-28 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_facture_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='facture_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
