# Generated by Django 3.2.1 on 2024-04-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_auto_20240428_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
