# Generated by Django 3.2.1 on 2024-04-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_alter_facture_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='total',
        ),
    ]
