# Generated by Django 3.2.1 on 2024-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_remove_facture_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
