# Generated by Django 3.2.1 on 2024-04-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_alter_facture_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureproduct',
            name='price_finich',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
